GPOoh r conversion
Public-Health-Scotland/source-linkage-files pull request #199
Opened 2022-04-28 08:30 UTC by Jennit07

I think this is almost ready. Definitely needs more testing/formatting but i thought i would submit the PR as i can't figure out some parts and wonder if you had any suggestions on how to write some of the code. I started to join the scripts together but then got a bit confused while testing so i've kept these separate for now and will put them into one script once finalised.

One part i am not sure of is line 103 in `extract_GPOoH_Diagnosis` in SPSS we take the first position of `.` and assign this to `diag1` to `diag6` but when i use `stringr::str_locate` i think this returns a vector which then doesn't let me do a pivot wider to create diag1 to diag6. Any thoughts on how to do this differently/improvements? This is the error returned when trying to do pivot wider:

`Error: Can't recycle ..1 (size 10) to match ..2 (size 5).
Run rlang::last_error() to see where the error occurred.`

 Still to do on this PR: 
- [ ] Create diag1 to diag6 variables with the read codes assigned accordingly by position of `.` 
- [ ] Any improvements to code where this can be simplified/run faster
- [ ] Join the 3 scripts together into one large script (kept this separate while testing)
- [ ] remove code where this writes to disk as we will store temp files as an object 
- [ ] check if there is a simpler way of doing things in R compared to SPSS code 

Closes #91

2022-05-03 08:34 UTC, catherineholland1 requested changes
some little changes

hope I found something that might help your `pivot_wider` ? I didn't know the desired result so unsure if found the desired fix

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_consultations.R
> +
I know in one of mine I removed the deletion of temporary files as in R you do not need to save these out, so unsure if required or not?

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_diagnosis.R
> +diagnosis_clean <- diagnosis_file %>%
```suggestion
diagnosis_read_codes <- diagnosis_file %>%
```

rename this and leave the `diagnosis_clean` for the next section dataframe name, I got an error so it allows sections to be tested separately

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_diagnosis.R
> +diagnosis_clean <- diagnosis_clean %>%
```suggestion
diagnosis_clean <- diagnosis_read_codes %>%
```

from above

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_diagnosis.R
> +    readcodelevel = str_locate(readcode, "[.]"),
```suggestion
    readcodelevel = str_locate(readcode, "[.]")[,1],
```

this creates 2 columns - numeric and description - so select the first column of this

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_diagnosis.R
> +  )
this now works with the above change

I don't know what is trying to be done to know if this works or not? 

```suggestion
  # restructure data
  pivot_wider(
   #id_cols = guid,
    names_from = readcodelevel,
    values_from = readcode
  )
```

additionally, removing this line perhaps? again I do not know the desired output but hopefully this helps get you there?

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_diagnosis.R
> +outfile <- outcome_clean %>%
what is `outcome_clean` ? is this a typo?

```suggestion
outfile <- diagnosis_clean %>%
```

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_diagnosis.R
> +
again, potentially remove if one script as no need to save out the temp files in R?
```suggestion

```

2022-05-03 08:34 UTC, catherineholland1 commented on Production_scripts/Process_extracts/extract_gp_ooh_outcomes.R
> +)
```suggestion

```

again remove temp files if one script

2022-05-27 14:14 UTC, Jennit07 commented
This PR is outstanding and needs a fresh set of eyes on this. I don't think i have dealt with creating diag1 to diag6 correctly and the script can definitely be cut down in places.

2022-06-16 14:48 UTC, Moohan commented
Just closing this while I work on it. I'll open a new PR in the future.

2022-06-16 14:48 UTC, closed without merging