Amend check mode
Public-Health-Scotland/source-linkage-files pull request #214
Opened 2022-05-16 09:01 UTC by Jennit07

I think I have captured everything here, however, if I have missed any, feel free to correct me. This now includes `...` as a parameter and will read the default file path as `.rds`. We can specify `ext = "zsav"` if we want to save or read the file in SPSS format and also specify `check_mode = "write"` if we want to write the file to disk. These file path functions are set to `read` by default as this is passed through the `get_file_path` function.

Scripts should now be in this format for writing to disk: 

SPSS: 
```r
# Reading
haven::read_sav(get_source_extract_path(year, "Outpatient", ext = "zsav"))
# Writing
haven::write_sav(get_source_extract_path(year, "Outpatient", ext = "zsav", check_mode = "write"), compress = "zsav")
```

R: 
```r
# Reading
readr::read_rds(get_source_extract_path(year, "Outpatients"))
# Writing
readr::write_rds(get_source_extract_path(year, "Outpatients", check_mode = "write"), compress = "xz")
```

I have also amended the LTCs script on this branch as I was changing file paths and came across an error. This now includes a new function `get_ltcs_path()` in the same format as others here. There was a part of the code where this was breaking as an older object was specified while trying to do a save. This has been amended and should now work.

2022-05-16 10:50 UTC, Moohan commented on Production_scripts/Create_slf_lookups/lookup_ltc.R
>    mutate(across(ends_with("date"), list(flag = ~ if_else(is.na(.x) | .x > end_fy, 0, 1)))) %>%
```suggestion
  mutate(across(ends_with("date"), list(flag = ~ if_else(is.na(.x) | .x > end_fy, 0L, 1L)))) %>%
```

2022-05-16 12:13 UTC, catherineholland1 approved these changes
all looks good

2022-05-17 10:27 UTC, Moohan requested changes
It looks like the Dev SOP is being deleted for some reason, could you do:
```
git fetch --all
git checkout origin/main-R -- R_development_SOP.md`
```
which should make sure you have the latest version on your branch.

Other than my comments it looks good! I think if we've missed/broken anything else we'll pick it up at some point soon on some other test and review process.

2022-05-17 10:27 UTC, Moohan commented on Production_scripts/Create_slf_lookups/lookup_gp_practice.R
> +  # order variables
I think `postcode` here refers to the postcode of the GP Practice? If so could we rename it to `gpprac_postcode` for clarity/readability, please?

2022-05-17 10:27 UTC, Moohan commented on Production_scripts/Create_social_care_lookups/lookup_sc_demographics.R
> +haven::write_sav(outfile, get_sc_demog_lookup_path(check_mode = "write"), compress = TRUE)
```suggestion
haven::write_sav(outfile, get_sc_demog_lookup_path(ext = "zsav", check_mode = "write"), compress = TRUE)
```

2022-05-17 10:27 UTC, Moohan commented on R/get_source_extract_path.R
>    ext <- match.arg(ext)
```suggestion
```

2022-05-27 14:08 UTC, Jennit07 commented
To do: I need to go back to this one and make the changes suggested

2022-05-30 09:59 UTC, Moohan commented
I re-requested a review from @catherineholland1, as I just dealt with all the merge conflicts and made a couple of other changes based on my previous comments.

2022-05-30 10:43 UTC, catherineholland1 approved these changes
ready for merge :)

2022-05-30 10:43 UTC, merged