Create pull_request_template.md
Public-Health-Scotland/source-linkage-files pull request #245
Opened 2022-05-31 10:37 UTC by Moohan

Creating a PR template, essentially to add a checklist to every PR for easy review.

I've tried to keep the checklist short - only the top-level / most important checks. Feel free to add / remove or edit.

2022-06-06 08:09 UTC, catherineholland1 approved these changes
looks good - nothing else to add from me. can add as we go if anything else pops to mind

2022-06-06 10:07 UTC, catherineholland1 requested changes
addition of bracket

2022-06-06 10:07 UTC, catherineholland1 approved these changes

2022-06-13 10:43 UTC, Jennit07 approved these changes
I think this looks good as well - we can add to this if anything else comes to mind

2022-06-13 10:44 UTC, merged