Cmh tests
Public-Health-Scotland/source-linkage-files pull request #328
Opened 2022-08-09 15:33 UTC by shintoLamp

Nothing special with this one, functionally the same as the NRS tests but with the variable `n_deaths` removed

2022-08-09 15:34 UTC, shintoLamp commented on Production_scripts/Process_extracts/extract_cmh.R
> +    year,
The script didn't select `year` before and I assumed this was an oversight as `year` was in the existing data

2022-08-12 08:50 UTC, Jennit07 requested changes
Looks good! Just one minor comment, im not sure if the other tests have n_episodes but i noticed we had this in the nrs deaths and checked the cmh SPSS code here which had it. We could maybe even add this flag into the demographic test flags? or just remember to hard code in the scripts

2022-08-12 08:50 UTC, Jennit07 commented on R/produce_source_cmh_tests.R
> +    create_hb_test_flags(hb_var = hbrescode) %>%
```suggestion
    create_hb_test_flags(hb_var = hbrescode) %>%
    dplyr::mutate(n_episodes = 1) %>%
```
Only thing not captured by the tests here is n_episodes which is in the SPSS code

2022-08-30 08:04 UTC, Jennit07 approved these changes

2022-08-30 08:48 UTC, merged