Change IT extract path functions
Public-Health-Scotland/source-linkage-files pull request #368
Opened 2022-08-23 15:32 UTC by shintoLamp

I have removed the function `it_extract_ref` so that this doesn't need to be changed every run. The functions in `get_it_extract_paths` now use regex to get the paths. 

In the case of PIS extracts, as there may be situations where we have multiple extracts matching the year given, I have given the user a prompt to select which matching file is the one they want to use. If there's only one matching file though, the prompt won't appear.

2022-08-24 11:02 UTC, Moohan requested changes
Great start, some comments and suggestions 🙂

2022-08-31 08:08 UTC, shintoLamp commented on R/get_it_extract_paths.R
> +    file_name_regexp = "SCTASK[0-9]{7}_LTCs.+",
Changed the regexp to the suggested one here

2022-08-31 08:09 UTC, shintoLamp commented on R/get_it_extract_paths.R
>    )
Added functionality based on this suggestion, please see changes

2022-08-31 08:10 UTC, shintoLamp commented on R/get_it_extract_paths.R
> +      }
Used this suggestion rather than the user-selection prompt

2022-08-31 08:58 UTC, shintoLamp commented on R/get_it_extract_paths.R
> +get_it_ltc_path <- function(...) {
Added this optional argument

2022-08-31 09:00 UTC, shintoLamp commented
Changed the functions based on suggestions, specifically large changes were made to `find_latest_file` and `get_it_prescribing_path`. I'm inexperienced with how arguments are passed through functions so I'm not sure that the `selection_method` argument is in the right place, but it does work.

2022-09-02 14:06 UTC, Jennit07 commented
> Changed the functions based on suggestions, specifically large changes were made to `find_latest_file` and `get_it_prescribing_path`. I'm inexperienced with how arguments are passed through functions so I'm not sure that the `selection_method` argument is in the right place, but it does work.

Great work Bateman, this is looking really good. I've tested the function and happy its working as we would expect. There are some nice checks in this and the use of regex will be very useful further down the line. For example: we have a 'new' task number but want to run one of the older years where this will be different. This accounts for this example perfectly. 

I think this is almost ready to merge - i did a check on the build tab and it looks like some of the tests are failing due this being old code which you have just changed e.g. IT extract ref number. Could you have a look at the 3 tests that are failing please and either delete or amend this to work with the new changes. Thanks :)

2022-09-02 14:07 UTC, Jennit07 requested changes
Some tests are failing on the build check, could you amend this please? Other than that, almost ready to merge

2022-09-06 08:38 UTC, Jennit07 approved these changes

2022-09-06 08:53 UTC, merged