extract_alarm_telecare.R
Public-Health-Scotland/source-linkage-files pull request #394
Opened 2022-09-28 13:39 UTC by lizihao-anu

A draft for extract_alarm_telecare.R, which converts B17 spss script to R.

2022-09-28 15:46 UTC, Moohan requested changes
A few changes to make. Please request my review again when you've split the code out into separate scripts and had a look at the other changes 👍

2022-09-28 15:46 UTC, Moohan commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +  )
This should be in a separate script - only the below is dependant on year

We will have 2 scripts; This code should be in `"Production_scripts/Social_Care/alarm_telecare.R"` and the year specific code will be in `"Production_scripts/Process_extracts/extract_alarm_telecare.R"`

2022-09-28 15:46 UTC, Moohan commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +    "/conf/sourcedev/Source_Linkage_File_Updates/{year}/Client_for_Source-20{year}"
`readr::read_rds(get_source_extract_path(year, type = "Client"))`

2022-09-28 15:46 UTC, Moohan commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +  ))
You will need to add the correct path for the alarm and telecare extract to the `get_source_extract_path` function.
```suggestion
  ) %>%
  write_rds(get_source_extract_path(year, type = "alarm_telecare", check_mode = "write"))
```

2022-09-28 15:46 UTC, Moohan commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +    )) %>%
Can you use the function `is_date_in_fyyear` here?

2022-09-28 15:46 UTC, Moohan commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +))
```suggestion
sc_demographics <- readr::read_rds(get_sc_demog_lookup_path())
```

2022-09-28 15:46 UTC, Moohan commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +  fs::path("/conf/hscdiip/SLF_Extracts/Social_care")
This shouldn't be needed
```suggestion
```

2022-09-28 15:46 UTC, Moohan commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +  tidylog::mutate(
We can drop the usage of tidylog
```suggestion
  tidylog::mutate(
```

2022-09-30 14:55 UTC, Moohan requested changes
Looking good, just some minor changes, which I think you should be able to commit directly on GitHub.

I haven't actually tried running the code yet, so I'll do that on my next pass!

2022-10-04 09:35 UTC, lizihao-anu commented on Production_scripts/Process_extracts/extract_alarm_telecare.R
> +# Transform B17 ----
Not from SPSS. Just my personal comment which I forgot to delete

2022-10-10 12:53 UTC, Jennit07 commented
> Looks good. I would be happy to approve except it looks like the Social Care data wasn't working... I was receiving 0 rows for any query I tried to do!
> 
> Hopefully it will be working next week and @Jennit07 can test the code and give final approval.

I've tested this through and happy it is working as expected. I've committed a few minor changes and it is now ready to merge

2022-10-10 12:54 UTC, Jennit07 approved these changes
I've made a few minor commits, but this is now ready to merge

2022-10-10 12:54 UTC, Jennit07 commented on Production_scripts/Social_Care/alarm_telecare.R
> +  write_rds(get_sc_hc_episodes_path(check_mode = "write"))
New function `get_sc_at_episodes_path` saves Alarms Telecare data in the same location as other social care extracts

2022-10-10 12:54 UTC, Jennit07 commented on Production_scripts/Social_Care/alarm_telecare.R
> +  left_join(pre_compute_record_dates, by = "period") %>%
Changes made

2022-10-10 12:59 UTC, merged