378 alarms + telecare year specific tests
Public-Health-Scotland/source-linkage-files pull request #407
Opened 2022-10-11 13:38 UTC by lizihao-anu

close #378

2022-10-17 13:01 UTC, Jennit07 commented on R/produce_at_sds_episodes_tests.R
> +produce_at_sds_episodes_tests <- function(data) {
```suggestion
produce_sc_at_tests <- function(data) {
```
Can we rename to this please? I was getting confused with having SDS in the name for this function as we should split these and make them specific to the tests

2022-10-17 13:32 UTC, Jennit07 requested changes
Some comments

2022-10-17 13:32 UTC, Jennit07 commented on R/produce_at_sds_episodes_tests.R
> +      )
```suggestion
    # keep variables for comparison
    dplyr::select(c(.data$valid_chi:.data$West_Lothian))
```
See function: `produce_source_ch_tests` we can have this as a simlar format and select desirable variables. Check this is righ `valid_chi to west lothian` for selection but this reduces the line of code

2022-10-18 08:10 UTC, Jennit07 commented on R/produce_at_sds_episodes_tests.R
> +      )
try testing this code for selecting the last variable e.g. west lothian
dplyr::select(c(.data$valid_chi:dplyr::last_col()))

2022-11-02 10:53 UTC, Jennit07 commented on R/produce_source_at_tests.R
> +      n_missing_person_id = dplyr::if_else(is_missing(.data$person_id), 1, 0),
These variables are not needed here as there should be tests for the client file which contains all of these variables
```suggestion
```

2022-11-02 11:08 UTC, lizihao-anu commented
> I've made a few small changes and pushed the commits. Happy to merge

Cool. Merge now

2022-11-02 11:08 UTC, merged