Implement the `read_file` function
Public-Health-Scotland/source-linkage-files pull request #586
Opened 2023-03-23 09:36 UTC by Moohan

On hold until #584 is merged.

2023-03-28 14:49 UTC, Jennit07 requested changes
Not sure if something weird going on in posit, but some of the changes in here are not showing for me in R e.g. `process_extract_alarms_telecare` doesnt look like its changed for me but it has on the git changes. I've made sure i'm up to date with the branch etc.

Some of them have also been missed like `read_lookup_xxx`. I need to spend a bit more time looking through this to double check/push any changes but i'll leave this on request changes for now. If anyone else has time to look at this feel free to pick it up this week, otherwise i'll come back to it on monday

2023-04-05 08:28 UTC, Jennit07 commented on R/process_extract_alarms_telecare.R
>    client_table <- readr::read_rds(client_lookup_path)
```suggestion
  client_table <- read_file(client_lookup_path)
```

2023-04-05 13:46 UTC, Moohan commented
> Hey @Moohan I've pushed some changes, can you please check you are happy with them? Then I'll approve/merge. Thanks

Looks good to me!

2023-04-07 06:50 UTC, Jennit07 approved these changes
Ready to merge

2023-04-07 06:50 UTC, merged