Write parquet
Public-Health-Scotland/source-linkage-files pull request #632
Opened 2023-04-18 15:53 UTC by lizihao-anu

2023-04-18 16:12 UTC, Moohan requested changes
A couple of minor points. Also, the file extension should just be `.parquet` not `.gz.parquet` sorry if it was confusing this morning!

2023-04-18 16:12 UTC, Moohan commented on R/write_data.R
> +    compression = compression,
I think we can just hardcode the compression type as I can't think of a reason why we wouldn't use it, or use anything different.

```suggestion
#' @param ... Additional arguments to [write_parquet()][arrow::write_parquet()].
#' @return `write_parquet()` returns the input `data` invisibly.
#' @export
#'
#' @family write out data
write_parquet <- function(data, path, ...) {
  arrow::write_parquet(
    x = data,
    sink = path,
    compression = "zstd",
```

2023-04-18 16:12 UTC, Moohan commented on R/write_data.R
> +    version = "2.4",
I think we should use `"latest"` here, or not include it at all, so it just uses `arrow::write_parquet()`'s default. By hardcoding the default to be anything else, there's a danger we are needlessly using an older version of the file specification which could eventually be deprecated.
```suggestion
    version = "latest",
```

2023-04-20 07:47 UTC, Moohan reviewed
Just swapped the extensions from `.gz.parquet` to `.parquet`

2023-04-20 07:47 UTC, Moohan commented on R/get_cohorts_paths.R
> +    file_name = stringr::str_glue("demographic_cohorts_{year}.gz.parquet"),
```suggestion
    file_name = stringr::str_glue("demographic_cohorts_{year}.parquet"),
```

2023-04-20 07:47 UTC, Moohan commented on R/get_cohorts_paths.R
> +    file_name = stringr::str_glue("Service_Use_Cohorts_{year}.gz.parquet"),
```suggestion
    file_name = stringr::str_glue("Service_Use_Cohorts_{year}.parquet"),
```

2023-04-20 07:47 UTC, Moohan commented on R/get_ltcs_path.R
> +    file_name = stringr::str_glue("LTCs_patient_reference_file-20{year}.gz.parquet"),
```suggestion
    file_name = stringr::str_glue("LTCs_patient_reference_file-20{year}.parquet"),
```

2023-04-20 07:47 UTC, Moohan commented on R/get_nsu_paths.R
> +    file_name = stringr::str_glue("All_CHIs_20{year}.gz.parquet"),
```suggestion
    file_name = stringr::str_glue("All_CHIs_20{year}.parquet"),
```

2023-04-20 07:47 UTC, Moohan commented on R/get_sparra_hhg_paths.R
> +    file_name = stringr::str_glue("HHG-20{year}.gz.parquet"),
```suggestion
    file_name = stringr::str_glue("HHG-20{year}.parquet"),
```

2023-04-20 07:47 UTC, Moohan commented on R/get_sparra_hhg_paths.R
> +    file_name = stringr::str_glue("SPARRA-20{year}.gz.parquet"),
```suggestion
    file_name = stringr::str_glue("SPARRA-20{year}.parquet"),
```

2023-04-20 07:54 UTC, Moohan commented
As we discussed, the `write_parquet` function needs implementing in place of the existing `write_rds` functions. This could possibly done through a new `write_file` function wich would be analogous to `read_file`

2023-04-20 13:54 UTC, Moohan commented
> @check-spelling-bot apply [updates](https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/4755081971/attempts/1).

2023-04-25 09:35 UTC, Moohan commented on R/write_file.R
> +    "parquet" = arrow::write_parquet(data, path, ...)
This would use your custom version of `write_parquet`.
```suggestion
    "parquet" = write_parquet(data, path, ...)
```

2023-04-25 09:35 UTC, Moohan commented on R/write_file.R
> +    "gz" = readr::write_csv(data, path, ...),
I don't *think* we need to support any of these types for writing out files... Maybe csv, definitely not the SPSS `sav` and `zsav` formats though?
```suggestion
```

2023-04-25 09:38 UTC, lizihao-anu commented
Thanks for James' brilliant idea. It is ready to be reviewed again.

2023-04-25 09:40 UTC, lizihao-anu commented
Cool

2023-04-26 14:45 UTC, Moohan approved these changes

2023-04-26 14:45 UTC, merged