758 investigate extracts to identify areas of code which can be cut down for processing times
Public-Health-Scotland/source-linkage-files pull request #899
Opened 2024-01-22 18:20 UTC by lizihao-anu

As discussed in #758, two functions, `process_sc_all_sds` and `process_sc_all_alarms_telecare`, take a very long time to execute. I have re-written the functions using `data.table` to improve the efficiency, including the speed and memory usage. The improvement is ridiculously significant.

Here's a summary comparing the improvements in two functions, `process_sc_all_sds` and `process_sc_all_alarms_telecare`:

| Function Name              | Old Method    | New Method    | Improvement   |
|---------------------------|---------------|---------------|---------------|
| `process_sc_all_sds`      | 24.94 mins | 1.69 mins | 94% reduction |
| `process_sc_all_alarms_telecare` | 31.81 mins | 0.81 mins | 98% reduction |

In both cases, the new methods produce identical results to the old methods but demonstrate significant reductions in running time. The `process_sc_all_sds` function saw a 94% reduction in running time, while the `process_sc_all_alarms_telecare` function experienced an even more impressive 98% reduction. These improvements are a testament to the effectiveness of the rewritten functions in optimizing their performance.

2024-01-24 17:27 UTC, SwiftySalmon commented on R/process_sc_all_sds.R
> +  matched_sds_data <- all_sds_extract %>%
need to change this back to data

2024-01-24 17:29 UTC, SwiftySalmon requested changes
Ran the sds code and it's much much faster. 

Only issue is that I've made a lot of changes to the sds code! Might need to merge my pull request and then make some changes to this one?

2024-01-25 09:33 UTC, lizihao-anu commented
> Ran the sds code and it's much much faster.
> 
> Only issue is that I've made a lot of changes to the sds code! Might need to merge my pull request and then make some changes to this one?

Yes. I agree. We can merge your changes to sds first, and the I can rewrite the code for sds.

2024-01-26 14:32 UTC, Jennit07 commented on R/process_sc_all_sds.R
> +      sds_option_3 = tidyr::replace_na(sds_option_3, 0)
Im wondering about this part of code as the variable `smrtype` codes the 4 options for SDS. If we are splitting them out into their own variables i think we would need to let people know in the email and also update the episode file layout workbook. Has this been split out due to how data table works?

Im not too familiar with working with code in data table. Do you have any links to any documentation to help my understanding? thanks

2024-01-26 14:37 UTC, Jennit07 commented on R/process_sc_all_sds.R
> +      sds_option_3 = tidyr::replace_na(sds_option_3, 0)
checked the final output and these variables are not there so i think it is fine. I think it is how i am reading the code!

2024-02-07 14:30 UTC, Jennit07 commented
Hi @lizihao-anu PR #900 has now merged. When you are back from A/L would you be able to have a look at the SDS code again and make any changes to have this in data table code please? Thanks!

2024-02-28 12:33 UTC, lizihao-anu commented
Ready to merge

2024-02-28 12:45 UTC, Jennit07 approved these changes

2024-02-28 12:46 UTC, merged